Reference vitest/config types in vite.config.ts to fix build error
Was seeing this:

vite.config.ts:7:3 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.

7   test: {
    ~~~~

  node_modules/vite/dist/node/index.d.ts:3106:18
    3106 declare function defineConfig(config: UserConfigExport): UserConfigExport;
                          ~~~~~~~~~~~~
    The last overload is declared here.

Found 1 error in vite.config.ts:7